# version: '3.8'
 
# services:
#   minio:
#     image: minio/minio:latest
#     container_name: minio
#     restart: always
#     ports:
#       - "9000:9000"   # Main MinIO API
#       - "9001:9001"   # Web console
#     environment:
#       MINIO_ROOT_USER: minioadmin
#       MINIO_ROOT_PASSWORD: minioadmin123
#     volumes:
#       - ./minio_data:/data
#     command: server /data --console-address ":9001"



version: '3.8'
 
services:
  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"   # Main MinIO API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_db
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - postgres
      - minio
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    entrypoint: ["./wait-for-postgres.sh", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]


  # React Frontend
  frontend:
    build: ./frontend_V01
    container_name: frontend
    restart: always
    depends_on:
      - backend
      - minio
    env_file:
      - ./frontend_V01/.env
    ports:
      - "3000:5173"

volumes:
  pg_data:
  minio_data:
